development:
  adapter: mysql
  database: mqlite_dev
  username: mqlite
  password: GtwXb8jQuAX2jpdf
  host: localhost
test:
  adapter: mysql
  database: mqlite_test
  username: mqlite
  password: GtwXb8jQuAX2jpdf
  host: localhost
production:
  adapter: mysql
  database: mqlite_prod
  username: mqlite
  password: GtwXb8jQuAX2jpdf
  host: localhost
